# Optional: Docker Compose file for PostgreSQL
version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
